### PR TITLE
Add logic to show light content (white) status bar on all view controllers

### PR DESCRIPTION
**Pull request by ryancarlson**
- status bar will be shown by default, with option to hide it
 - tract view controller will opt to hide it

### CODE REVIEW

**Comment by ryancarlson** [comment]
@michaelharro can you review this small PR?

**Comment by ryancarlson** [comment]
Thanks. Actually though this change suggests that the background is black and therefore the status bar content is white. The end result is this: 
simulator screen shot may 22 2017 3 24 26 pm

**Comment by michaelharro** [comment]
ok, I wasn't paying much attention to the specifics. I just saw you used the correct technique and was going to do a visual check. It looks correct so it is good to go

**Comment by ryancarlson** [comment]
Cool, thanks!

**Pull request merged**
