### PR TITLE
GT-1943 Refactor OnboardingTutorialView from UIKit to SwiftUI

### PR DESCRIPTION
**Pull request by levieggertcru**
This PR refactors OnboardingTutorialView in ```Features/Onboarding/OnboardingTutorial/``` from UIKit to SwiftUI.

### CODE REVIEW

**Review by rachaelblue — COMMENTED** [review]
Hey @levieggertcru, some of the spacing looks a little off.

Screen Shot 2023-02-28 at 2 30 57 PM

I don't think the animations were quite that big before, were they?
Screen Shot 2023-02-28 at 2 31 11 PM

**Comment by levieggertcru** [comment]
Good find that is a bit off.  I didn't check those larger devices and devices without the home button, will look into making that more consistent.

**Comment by levieggertcru** [comment]
This is ready for a second look.  There were a few things I needed to do to keep a little more consistent with UIKit.
1. Set the GodTools logo image width relative to the screen width and also maintain the aspect ratio.
2. Set the animation frame width relative to the screen width and also apply aspect ratio.
3. Centered the GodTools logo and watch video button vertically by applying Spacer() views.
4. Applied a Spacer() view below the animations and the Text titles for the animations have a top padding that is relative to the height of the screen.

**Review by rachaelblue — APPROVED** [review]
Looks good!

**Pull request merged**
