### PR TITLE
GT Upload code coverage reports to CruGlobal codecov account

### PR DESCRIPTION
**Pull request by levieggertcru**
This PR is enabling code coverage reports to be uploaded to codecov under CruGlobal/godtools-swift

- Point ```godtools``` scheme Tests to Production build configuration.
- Add upload codecov reports in workflow.
- Enable godtools-swift in codecov CruGlobal account https://app.codecov.io/gh/CruGlobal/godtools-swift and add token to GitHub secrets

### CODE REVIEW

**Comment by frett** [comment]
I just requested the codecov GitHub app is actually added to the godtools-swift repo. that might be what is necessary to report coverage

**Comment by levieggertcru** [comment]
Hey @frett what did you?  

Was it something here -> https://app.codecov.io/gh/CruGlobal

**Comment by frett** [comment]
It's not able to process whatever file codecov is uploading automatically. https://app.codecov.io/github/CruGlobal/godtools-swift/commit/82c750e2a7ca39e5b22f546588978055254ed5df

Screenshot 2023-05-12 at 8 55 44 AM

**Comment by levieggertcru** [comment]
Hey @frett I created a task for this and will come back later to see if I can get Xcode generated reports uploading to CruGlobal code coverage. ```https://jira.cru.org/browse/GT-2039```.  Otherwise I may end up using something with Fastlane ```https://docs.fastlane.tools/actions/xcov/```.

It seems the code cov action is grabbing reports generated from Fastlane and trying to do something with those rather than the Xcode generated reports.

**Pull request merged**
