### PR TITLE
GT-2018 pin social sign in buttons to bottom and center image in remaining space

### PR DESCRIPTION
**Pull request by rachaelblue**

### CODE REVIEW

**Review by levieggertcru — DISMISSED** [review]

**Comment by levieggertcru** [comment]
Hey @rachaelblue just noticed something when viewing the iPhone 8 and iPhone 8 plus that the text is getting clipped.

iphone-8-plus

iphone-8

**Comment by levieggertcru** [comment]
Hey @rachaelblue also I didn't realize this originally, but we will need to change the text based on whether someone taps Login vs Create Account.

sign-in-vs-create-account

**Comment by rachaelblue** [comment]
Thanks @levieggertcru!  Fixed the text getting cropped and updated the strings.

**Comment by levieggertcru** [comment]
Looks good!

**Review by levieggertcru — APPROVED** [review]

**Pull request merged**
