### PR TITLE
GT-2323 observe the new force language name flag

### PR DESCRIPTION
**Pull request by gyasistory**

### CODE REVIEW

**Comment by levieggertcru** [comment]
Hey @rachaelblue these changes look right to me.  I updated the tests to include the ```forceLanguageName``` (https://github.com/CruGlobal/godtools-swift/pull/2237).

**Comment by rachaelblue** [comment]
Hey @levieggertcru, how do you want to handle language direction on `LanguageModel`?  Do you want to keep `LanguageDirectionDomainModel`?  Seems like you were moving towards different models having their own version of the direction enum?

**Comment by levieggertcru** [comment]
Hey @rachaelblue  yeah I'd say keep the ```LanguageDirectionDomainModel```.

**Comment by levieggertcru** [comment]
I was starting to move the renderer towards pointing to the domain layer.  The renderer is it's own beast though.

**Comment by rachaelblue** [comment]
Ok thanks @levieggertcru!

**Review by levieggertcru — DISMISSED** [review]
Thanks @rachaelblue for making those extra updates!

**Review by levieggertcru — APPROVED** [review]

**Comment by levieggertcru** [comment]
@rachaelblue going to wait to hear back from Jill and Aaron to see if they want this to go into the next release version 6.3.3 before approving for merger.

**Review by levieggertcru — APPROVED** [review]

**Comment by frett** [comment]
> @rachaelblue going to wait to hear back from Jill and Aaron to see if they want this to go into the next release version 6.3.3 before approving for merger.

The android version of this was already merged and will be in the version we push out with the new languages

**Comment by levieggertcru** [comment]
Thanks @frett!

**Pull request merged**
